binance_coins = """
BTC_USDT,ETH_USDT,ETH_BTC,BNB_BTC,LINK_BTC,BNB_USDT,LTC_USDT,CMT_BTC,XRP_BTC,BCHABC_USDT,LINK_USDT,
EOS_USDT,BTC_USDC,LTC_BTC,BCHABC_BTC,XRP_USDT,BTC_PAX,FTM_BTC,EOS_BTC,BTC_TUSD,REN_BTC,MATIC_BTC,
TRX_USDT,ADA_BTC,CELR_BTC,ONE_BTC,MANA_BTC,AST_BTC,USDC_USDT,TUSD_USDT,ADA_USDT,PAX_USDT,MATIC_USDT,
BTT_USDT,NEO_USDT,RVN_BTC,TRX_BTC,FTM_USDT,ONE_USDT,BQX_BTC,ALGO_BTC,NEO_BTC,XMR_BTC,BTT_BTC,ALGO_USDT,
WTC_BTC,FET_USDT,CELR_USDT,XLM_BTC,MTH_BTC,TNT_BTC,BAT_BTC,POWR_BTC,ZIL_BTC,HC_BTC,HOT_BTC,HOT_USDT,
LINK_ETH,WAVES_BTC,QTUM_BTC,VET_BTC,ATOM_BTC,QTUM_USDT,ICX_BTC,BNB_ETH,CMT_ETH,VET_USDT,ZEC_BTC,
ETC_USDT,FET_BTC,VIBE_BTC,ETH_USDC,ETH_PAX,LTC_BNB,XRP_BNB,DENT_BTC,AGI_BTC,ONE_BNB,XLM_USDT,GVT_BTC,
ONT_BTC,QKC_BTC,ICX_USDT,NANO_BTC,DASH_BTC,ONT_USDT,IOTA_BTC,NULS_BTC,ZIL_USDT,CMT_BNB,ATOM_USDT,LTC_TUSD,
DOCK_BTC,MATIC_BNB,XMR_USDT,ARN_BTC,FUN_BTC,PHB_BTC,XZC_BTC,IOST_BTC,HOT_ETH,NULS_USDT,EVX_BTC,XEM_BTC,ETC_BTC,
CDT_BTC,IOTX_BTC,EOS_ETH,NPXS_BTC,BNB_USDC,MITH_BTC,MTL_BTC,ENJ_BTC,WAVES_USDT,VIB_BTC,IOTA_USDT,BAT_USDT,XVG_BTC,
BCPT_BTC,MITH_USDT,TRX_ETH,XRP_ETH,LTC_PAX,YOYO_BTC,ZRX_BTC,THETA_BTC,CELR_BNB,USDC_PAX,ETH_TUSD,FTM_BNB,MANA_ETH,
ZEC_USDT,PPT_BTC,EOS_BNB,LINK_USDC,WAN_BTC,STRAT_BTC,OMG_BTC,NPXS_ETH,BTT_BNB,REN_BNB,ELF_BTC,MDA_BTC,FUEL_BTC,
LTC_ETH,ADA_BNB,KMD_BTC,GNT_BTC,SNM_BTC,NCASH_BTC,DATA_BTC,TFUEL_USDT,TRX_BNB,AION_BTC,GTO_BTC,WABI_BTC,DLT_BTC,I
OST_USDT,BRD_BTC,MFT_BTC,MCO_BTC,INS_BTC,TNB_BTC,OAX_BTC,REQ_BTC,STORJ_BTC,LOOM_BTC,OMG_USDT,PAX_TUSD,NAS_BTC,EOS_PAX,
ALGO_BNB,REP_BTC,ADA_ETH,APPC_BTC,ARK_BTC,LINK_TUSD,BTS_BTC,RCN_BTC,TFUEL_BTC,LSK_BTC,QLC_BTC,NANO_USDT,BNB_TUSD,
RVN_BNB,SYS_BTC,LTC_USDC,XRP_PAX,AE_BTC,RDN_BTC,BTG_BTC,WPR_BTC,DNT_BTC,POE_BTC,KNC_BTC,BNB_PAX,GRS_BTC,AST_ETH,
AMB_BTC,ZRX_USDT,NEBL_BTC,VIA_BTC,LEND_BTC,BTC_USDS,STEEM_BTC,DASH_USDT,THETA_USDT,SKY_BTC,USDC_TUSD,NEO_ETH,
DENT_ETH,RLC_BTC,NAV_BTC,VET_ETH,GO_BTC,TRX_XRP,XRP_TUSD,DCR_BTC,POA_BTC,ARDR_BTC,LUN_BTC,LRC_BTC,ICX_ETH,BQX_ETH,
HOT_BNB,BLZ_BTC,OST_BTC,ADX_BTC,PIVX_BTC,ZIL_ETH,SNGLS_BTC,ATOM_BNB,POWR_ETH,GXS_BTC,QSP_BTC,ENG_BTC,ADA_TUSD,NEO_BNB,
NEO_USDC,VET_BNB,ZIL_BNB,CVC_BTC,BCD_BTC,POLY_BTC,XRP_USDC,EDO_BTC,HC_ETH,SC_BTC,USDS_USDT,GAS_BTC,BCHABC_PAX,ZEN_BTC,
XMR_ETH,ENJ_USDT,SNT_BTC,DGD_BTC,BCHABC_TUSD,FET_BNB,MTH_ETH,BCHABC_USDC,TNT_ETH,WTC_ETH,MITH_BNB,BAT_ETH,IOST_ETH,
POWR_BNB,MFT_ETH,CND_BTC,NXS_BTC,MFT_BNB,ADA_USDC,KEY_BTC,EOS_TUSD,GTO_USDT,WAVES_ETH,XMR_BNB,EVX_ETH,VIBE_ETH,LINK_PAX,
BRD_BNB,NANO_BNB,REP_ETH,OMG_ETH,QKC_ETH,DASH_ETH,NEO_TUSD,TRX_USDC,NEO_PAX,ZEC_ETH,IOTA_ETH,STORM_BTC,XZC_ETH,WTC_BNB,
NULS_BNB,TFUEL_BNB,XLM_ETH,NCASH_ETH,XLM_BNB,ONT_BNB,WAN_BNB,GVT_ETH,ONG_BTC,TRX_TUSD,ONG_USDT,XLM_USDC,WAN_ETH,PPT_ETH,T
HETA_ETH,VIB_ETH,ONE_USDC,EOS_USDC,LOOM_ETH,XVG_ETH,RDN_ETH,BAT_BNB,AGI_ETH,PHB_BNB,IOTA_BNB,DOCK_ETH,ZRX_ETH,USDS_PAX,
ZEC_BNB,ONT_ETH,SNM_ETH,IOTX_ETH,ENJ_ETH,FUN_ETH,DASH_BNB,QTUM_BNB,NANO_ETH,NAS_ETH,WAVES_TUSD,AE_ETH,WAVES_BNB,USDS_USDC,
MCO_ETH,AGI_BNB,YOYO_ETH,ICX_BNB,ARN_ETH,MDA_ETH,SYS_BNB,AION_ETH,INS_ETH,BTT_USDC,CDT_ETH,QTUM_ETH,REQ_ETH,NAS_BNB,
BRD_ETH,BTT_TUSD,BNT_BTC,KNC_ETH,NULS_ETH,GTO_BNB,XZC_XRP,BCPT_BNB,XEM_ETH,GTO_ETH,ETC_BNB,ELF_ETH,IOST_BNB"""


def pick_shitcoins(allowed_counter_currencies, num_shitcoins=None, excluded_pairs=['ETH_BTC', 'ETH_USDT', 'BTC_USDT']):

    result = []

    for pair in binance_coins.split(','):
        pair = pair.strip()
        transaction_currency, counter_currency = pair.split('_')
        if counter_currency in allowed_counter_currencies and not pair in excluded_pairs:
            result.append(pair)
    if num_shitcoins is None:
        return result

    return result[:num_shitcoins]


if __name__ == '__main__':
    shitcoins = pick_shitcoins(['BTC'], 50)
    print(shitcoins)
    print(f'{len(shitcoins)} selected.')