# Generated by Django 2.1.2 on 2019-05-15 13:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20181027_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
