# Generated by Django 2.1.2 on 2018-12-06 13:22

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_start_timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('train_end_timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('experiment_id', models.TextField()),
                ('rank', models.IntegerField()),
                ('representation', models.TextField()),
                ('metric_id', models.SmallIntegerField()),
                ('metric_value', models.FloatField()),
            ],
        ),
    ]
