# Generated by Django 2.1.2 on 2019-01-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doge', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doge',
        ),
    ]
