# Generated by Django 2.1.2 on 2019-03-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio_rebalanced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField(max_length=15)),
                ('committee_id', models.TextField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Allocation')),
            ],
        ),
    ]
