# Generated by Django 2.1.2 on 2019-03-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_allocationcommittee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationcommittee',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='allocationcommittee',
            name='horizon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
