# Generated by Django 2.1.2 on 2019-04-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20190327_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationcommittee',
            name='vote',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allocationcommittee',
            name='voted_at',
            field=models.DateTimeField(default='2018-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
